export { default as Blog } from './blog/Blog'
export { default as Top_Restaurantes } from './top_restaurantes/Top_Restaurantes'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Carrusel } from './carrusel/Carrusel'